# CSS (assets/styles.css)
# JS (assets/app.js, assets/search.js, etc.)
# Fonts (assets/fonts/*.woff2)
# Images/icons (icons/*.svg, *.png, etc.)
# are cached heavily. HTML files update immediately, so you don’t need a version there.

# Automates cache busting and deployment of the documentation site.
# Replaces placeholders with hashed versions before publishing to GitHub Pages.
# ignore in scripts, fonts, onnx_model and images directories, and .md files.
# exclude scripts, markdown, fonts, models, and images from both replacement and verification.

name: Cache Busting & Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify artifacts exist
        run: |
          test -f docs/assets/data/library.{{DB_VERSION}}.sqlite || true
          test -f docs/assets/data/library.sqlite || true
          test -d docs/assets/data/semantic || { echo "docs/assets/data/semantic not found"; exit 1; }

      - name: Compute versions
        shell: bash
        run: |
          set -euo pipefail

          APP_VERSION="${GITHUB_SHA::8}"

          DB_PATH="docs/assets/data/library.sqlite"
          if [ ! -f "$DB_PATH" ] && ls docs/assets/data/library.*.sqlite >/dev/null 2>&1; then
            DB_PATH="$(ls docs/assets/data/library.*.sqlite | head -n1)"
          fi

          if [ -f "$DB_PATH" ]; then
            DB_VERSION="$(sha256sum "$DB_PATH" | awk '{print $1}' | cut -c1-12)"
          else
            DB_VERSION="devdb000000"
          fi

          SEM_DIR="docs/assets/data/semantic"
          SEM_VERSION="$(
            find "$SEM_DIR" -type f -print0 \
            | sort -z \
            | xargs -0 sha256sum \
            | sha256sum \
            | awk '{print $1}' \
            | cut -c1-12
          )"

          echo "APP_VERSION=$APP_VERSION" >> "$GITHUB_ENV"
          echo "DB_VERSION=$DB_VERSION"   >> "$GITHUB_ENV"
          echo "SEM_VERSION=$SEM_VERSION" >> "$GITHUB_ENV"

      - name: Replace placeholders in assets
        run: |
          set -euo pipefail

          EXCLUDES='
            -path docs/scripts -prune -o
            -path docs/assets/fonts -prune -o
            -path docs/assets/images -prune -o
            -path docs/assets/data/semantic/onnx_model -prune -o
            -path docs/js/onyx -prune -o
            -path docs/js/sql_helpers -prune -o
            -name "*.md" -prune -o
          '

          replace_all() {
            local placeholder="$1" value="$2"
            shift 2
            eval find docs \( $EXCLUDES -type f -name "\"$1\"" -print \) -o -false | xargs -r sed -i "s|${placeholder}|${value}|g"
            eval find docs \( $EXCLUDES -type f -name "\"$2\"" -print \) -o -false | xargs -r sed -i "s|${placeholder}|${value}|g"
            eval find docs \( $EXCLUDES -type f -name "\"$3\"" -print \) -o -false | xargs -r sed -i "s|${placeholder}|${value}|g"
            eval find docs \( $EXCLUDES -type f -name "\"$4\"" -print \) -o -false | xargs -r sed -i "s|${placeholder}|${value}|g"
          }

          replace_all '{{VERSION}}'     "$APP_VERSION" '*.html' '*.css' '*.js' '*.json'
          replace_all '{{DB_VERSION}}'  "$DB_VERSION"  '*.html' '*.css' '*.js' '*.json'
          replace_all '{{SEM_VERSION}}' "$SEM_VERSION" '*.html' '*.css' '*.js' '*.json'

      - name: Verify replacements
        run: |
          set -euo pipefail
          grep -R -I "{{VERSION}}" docs \
            --exclude='*.md' \
            --exclude-dir=docs/scripts \
            --exclude-dir=docs/assets/fonts \
            --exclude-dir=docs/assets/images \
            --exclude-dir=docs/assets/data/semantic/onnx_model \
            --exclude-dir=docs/js/onyx \
            --exclude-dir=docs/js/sql_helpers \
            && { echo "Unreplaced {{VERSION}}"; exit 1; } || true

          grep -R -I "{{DB_VERSION}}" docs \
            --exclude='*.md' \
            --exclude-dir=docs/scripts \
            --exclude-dir=docs/assets/fonts \
            --exclude-dir=docs/assets/images \
            --exclude-dir=docs/assets/data/semantic/onnx_model \
            --exclude-dir=docs/js/onyx \
            --exclude-dir=docs/js/sql_helpers \
            && { echo "Unreplaced {{DB_VERSION}}"; exit 1; } || true

          grep -R -I "{{SEM_VERSION}}" docs \
            --exclude='*.md' \
            --exclude-dir=docs/scripts \
            --exclude-dir=docs/assets/fonts \
            --exclude-dir=docs/assets/images \
            --exclude-dir=docs/assets/data/semantic/onnx_model \
            --exclude-dir=docs/js/onyx \
            --exclude-dir=docs/js/sql_helpers \
            && { echo "Unreplaced {{SEM_VERSION}}"; exit 1; } || true

      - name: Stage versioned DB copy (optional immutable hosting)
        run: |
          set -euo pipefail
          SRC="docs/assets/data/library.sqlite"
          if [ -f "$SRC" ]; then
            DEST="docs/assets/data/library.${DB_VERSION}.sqlite"
            [ -f "$DEST" ] || cp "$SRC" "$DEST"
            echo "Staged $DEST"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
