# CSS (assets/styles.css)
# JS (assets/app.js, assets/search.js, etc.)
# Fonts (assets/fonts/*.woff2)
# Images/icons (icons/*.svg, *.png, etc.)
# are cached heavily. HTML files update immediately, so you don’t need a version there.

# Automates cache busting and deployment of the documentation site.
# Replaces placeholders with hashed versions before publishing to GitHub Pages.
# ignore in scripts, fonts, onnx_model and images directories, and .md files.
# exclude scripts, markdown, fonts, models, and images from both replacement and verification.

name: Cache Busting & Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify artifacts exist
        shell: bash
        run: |
          set -euo pipefail
          test -f docs/assets/data/library.{{DB_VERSION}}.sqlite || true
          test -f docs/assets/data/library.sqlite || true
          test -d docs/assets/data/semantic || { echo "docs/assets/data/semantic not found"; exit 1; }

      - name: Compute versions
        shell: bash
        run: |
          set -euo pipefail

          APP_VERSION="${GITHUB_SHA::8}"

          DB_PATH="docs/assets/data/library.sqlite"
          if [ ! -f "$DB_PATH" ] && ls docs/assets/data/library.*.sqlite >/dev/null 2>&1; then
            DB_PATH="$(ls docs/assets/data/library.*.sqlite | head -n1)"
          fi

          if [ -f "$DB_PATH" ]; then
            DB_VERSION="$(sha256sum "$DB_PATH" | awk '{print $1}' | cut -c1-12)"
          else
            DB_VERSION="devdb000000"
          fi

          SEM_DIR="docs/assets/data/semantic"
          SEM_VERSION="$(
            find "$SEM_DIR" -type f -print0 \
            | sort -z \
            | xargs -0 sha256sum \
            | sha256sum \
            | awk '{print $1}' \
            | cut -c1-12
          )"

          {
            echo "APP_VERSION=$APP_VERSION"
            echo "DB_VERSION=$DB_VERSION"
            echo "SEM_VERSION=$SEM_VERSION"
          } >> "$GITHUB_ENV"

      - name: Replace placeholders in assets
        shell: bash
        run: |
          set -euo pipefail

          prune_and_targets() {
            # Prune excluded directories. Only target text-like assets.
            find docs \
              \( -path docs/scripts \
                 -o -path docs/assets/fonts \
                 -o -path docs/assets/images \
                 -o -path docs/assets/data/semantic/onnx_model \) -prune -o \
              -type f \( -name "*.html" -o -name "*.css" -o -name "*.js" -o -name "*.json" \) \
              -print0
          }

          replace_all() {
            local placeholder="$1" value="$2"
            prune_and_targets | xargs -0 -r sed -i "s|${placeholder}|${value}|g"
          }

          replace_all '{{VERSION}}'     "$APP_VERSION"
          replace_all '{{DB_VERSION}}'  "$DB_VERSION"
          replace_all '{{SEM_VERSION}}' "$SEM_VERSION"

      - name: Verify replacements
        shell: bash
        run: |
          set -euo pipefail

          prune_and_scan() {
            # Same pruning as replace step; also exclude *.md implicitly by not targeting it.
            find docs \
              \( -path docs/scripts \
                 -o -path docs/assets/fonts \
                 -o -path docs/assets/images \
                 -o -path docs/assets/data/semantic/onnx_model \) -prune -o \
              -type f ! -name "*.md" -print0
          }

          check_placeholder() {
            local ph="$1"
            if prune_and_scan | xargs -0 grep -I -n -H -- "$ph" >/dev/null; then
              echo "Unreplaced $ph"
              exit 1
            fi
          }

          check_placeholder '{{VERSION}}'
          check_placeholder '{{DB_VERSION}}'
          check_placeholder '{{SEM_VERSION}}'

      - name: Stage versioned DB copy (optional immutable hosting)
        shell: bash
        run: |
          set -euo pipefail
          SRC="docs/assets/data/library.sqlite"
          if [ -f "$SRC" ]; then
            DEST="docs/assets/data/library.${DB_VERSION}.sqlite"
            [ -f "$DEST" ] || cp "$SRC" "$DEST"
            echo "Staged $DEST"
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
